mod auto_config;
mod capabilities;
mod catalog_state;
mod cognitive_runtime;
mod collab;
mod config;
mod deepseek;
mod group_chat;
mod mcp;
mod memory;
mod provider;
mod runtime;
mod runtime_paths;
mod skill_router;
pub mod studio;
mod task_manager;
mod update;

pub use auto_config::AutoConfigIntent;
pub use auto_config::AutoConfigResult;
pub use auto_config::apply_auto_config;
pub use auto_config::detect_auto_config;
pub use auto_config::update_installed_skill;
pub use capabilities::*;
pub use catalog_state::ConfiguredMcp;
pub use catalog_state::InstalledSkill;
pub use catalog_state::list_configured_mcp;
pub use catalog_state::list_installed_skills;
pub use catalog_state::remove_configured_mcp;
pub use catalog_state::remove_installed_skill;
pub use catalog_state::set_mcp_enabled;
pub use catalog_state::set_skill_enabled;
pub use catalog_state::get_mcp_config;
pub use catalog_state::upsert_mcp_config;
pub use cognitive_runtime::*;
pub use collab::*;
pub use deepseek::client::ChatState;
pub use deepseek::client::DeepSeekUser;
pub use deepseek::client::LoginResult;
pub use deepseek::client::SessionInfo;
pub use deepseek::client::chat_completion;
pub use deepseek::client::create_guest_challenge as deepseek_create_guest_challenge;
pub use deepseek::client::create_session;
pub use deepseek::client::login as deepseek_login;
pub use deepseek::client::login_by_mobile_sms as deepseek_login_by_mobile_sms;
pub use deepseek::client::send_sms_code as deepseek_send_sms_code;
pub use deepseek::client::validate_token as deepseek_validate_token;
pub use deepseek::client::read_chat_stream;
pub use deepseek::client::solve_pow_header;
pub use deepseek::pow::PowChallenge;
pub use deepseek::pow::PowSolution;
pub use deepseek::pow::guest_pow_header_json;
pub use deepseek::pow::pow_header_json;
pub use deepseek::pow::solve_challenge;
pub use group_chat::*;
pub use config::ModelChoice;
pub use config::ProviderConfig;
pub use config::ProviderDocument;
pub use config::ProviderKind;
pub use config::ProviderRegistry;
pub use config::ProviderSettings;
pub use config::RemoteCompactionMode;
pub use config::deepseek_account_settings;
pub use mcp::McpRuntime;
pub use mcp::McpServerStatus;
pub use mcp::McpServerConfig;
pub use memory::Memory;
pub use memory::MemoryLifecycle;
pub use memory::MemoryManager;
pub use memory::MemoryScope;
pub use memory::MemoryType;
pub use provider::HttpModelProvider;
pub use runtime::*;
pub use runtime_paths::*;
pub use skill_router::*;
pub use studio::*;
pub use task_manager::*;
pub use update::UpdateCheckResult;
pub use update::check_for_update;
